# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "RTK17"
product_name = "RTK17"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "havis"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P1_11", "P1_10", "P0_03", "P0_28"]
output_pins = ["P1_13", "P0_02", "P0_29", "P0_31", "P0_30"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = false

[layout]
rows = 4
cols = 5
layers = 2

matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4)
(1,0) (1,1) (1,2) (1,3) (1,4)
(2,0) (2,1) (2,2) (2,3) (2,4)
(3,0) (3,1) (3,2) (3,3) (3,4)
"""

# layer 0 (default):
# (the number comes from the order of '[[layer]] entries' in the file)
[[layer]]
name = "base_layer" #optional name for the layer
keys = """
ESC   Y     U I O P
F     G     H J K L  
Z     C     V B N M 
SPACE MO(1) _ _ _ _  
"""

# layer 1:
[[layer]]
name = "fn_layer" #optional name for the layer
keys = """
User0 User1 _  Clear Bootloader  
_     _     _  _     _    
A     B     C  D     E
_     _     _  _     _ 
"""

# Ble configuration
# To use the default configuration, ignore this section completely
[ble]
# Whether to enable BLE feature
enabled = true
# nRF52840's saadc pin for reading battery level, you can use a pin number or "vddh"
battery_adc_pin = "vddh"

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false